# LogoutLives config files.
# If you don't want to change anything or like the
# plugin bt itself, keep the defaults.
# Created by SandAx3r


# enableTitle: Show a title when an NPC dies
# - TRUE: enabled (default)
# - FALSE: disabled
enableTitle : TRUE
# mainTitle: Refers to the text that is shown in the title (If it is enabled)
# You can put whatever you want between "text".
mainTitle : "F (offline)"

# lighting: summons a lighting when an NPC dies
# - TRUE: enabled (default)
# - FALSE: disabled
lightning: TRUE
#lightningDamage: Whether the lightning should do damage.
# - "DAMAGE": Does damage
# - "NO DAMAGE": Doesn't do damage (default)
lightningDamage : "NO DAMAGE"

# sound: The sound that makes the NPC when it dies.
# - TRUE: enabled (default)
# - FALSE: disabled
enableSound : TRUE

# --------- NPC OPTIONS ---------

#canOpenDoors: Wheter NPCs are able to open doors
# - TRUE: enabled (default)
# - FALSE: disabled
canOpenDoors : TRUE

#dropsInventory: Wheter NPCs drop players inventory on death
# - TRUE: enabled (default)
# - FALSE: disabled
dropsInventory : TRUE
